In [3]:
import numpy as np

In [24]:
pi = np.array([.2, .4, .4]).reshape(3)
A = np.array([[.5, .5],
              [.4, .6],
              [.7 , .3]
              ])
B = np.array([[.5, .2, .3],
              [.3, .5, .2],
              [.2, .3, .5]])

In [29]:
R, W = A[:, 0], A[:, 1]
R, W

(array([0.5, 0.4, 0.7]), array([0.5, 0.6, 0.3]))

## 识别问题

In [52]:
o1 = pi * R
o1

array([0.1 , 0.16, 0.28])

In [37]:
s2 = o1.dot(B)
s2

array([0.154, 0.184, 0.202])

In [39]:
o2 = s2 * W
o2

array([0.077 , 0.1104, 0.0606])

In [41]:
s3 = o2.dot(B)
s3

array([0.08374, 0.08878, 0.07548])

In [42]:
o3 = s3 * R
o3

array([0.04187 , 0.035512, 0.052836])

In [44]:
sum(o3)

np.float64(0.130218)

## 学习算法

## 预测问题

In [51]:
so1 = pi * R
so1

array([0.1 , 0.16, 0.28])

In [70]:
so1_ = np.repeat(so1.reshape(1,3), 3, axis=0)
so1_

array([[0.1 , 0.16, 0.28],
       [0.1 , 0.16, 0.28],
       [0.1 , 0.16, 0.28]])

In [73]:
B

array([[0.5, 0.2, 0.3],
       [0.3, 0.5, 0.2],
       [0.2, 0.3, 0.5]])

In [71]:
so1_*B

array([[0.05 , 0.032, 0.084],
       [0.03 , 0.08 , 0.056],
       [0.02 , 0.048, 0.14 ]])

In [88]:
so2 = np.max(so1_*B , axis=1) 
so2

array([0.084, 0.08 , 0.14 ])

In [ ]:
so2 * W

In [81]:
so2_ = np.repeat(so2.reshape(1,3), 3, axis=0)
so2_

array([[0.084, 0.08 , 0.14 ],
       [0.084, 0.08 , 0.14 ],
       [0.084, 0.08 , 0.14 ]])

In [86]:
so3 = np.max(so2_*B , axis=1) 
so3

array([0.042, 0.04 , 0.07 ])

In [85]:
so3 * R

array([0.021, 0.016, 0.049])